### PR TITLE
linux: support columns in ThreadStatusDataProvider tree model

### PR DESCRIPTION
**Pull request by bhufmann**
Do not merge until https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/1149 is fixed.

Signed-off-by: Bernd Hufmann <bernd.hufmann@ericsson.com>

### CODE REVIEW

**Review by MatthewKhouzam — APPROVED** [review]
I was hesitant about exec, but it's everywhere in the kernel documentation.

**Comment by MatthewKhouzam** [comment]
We can call exec process. If and only if you want.

**Comment by bhufmann** [comment]
> We can call exec process. If and only if you want.

The string `Exec_name` is used as label in other analysis and views (e.g. `Scheuler Wakeup To Scheduler Switch Latency - Latency Table`). I think it should be consistent across views.

image

**Comment by MatthewKhouzam** [comment]
Approved!

**Pull request merged**
