### PR TITLE
ctf: support out of spec index files from LTTng

### PR DESCRIPTION
**Pull request by arfio**
IDX files were added to help speed up trace indexing. This patch will load them. This patch should not affect the system performance, but might lay down some groundwork to improve streaming performance.

The index format is not yet part of the CTF standard, but is described here:
https://git.efficios.com/?p=babeltrace.git;a=blob;f=src/plugins/ctf/fs-src/lttng-index.hpp;h=36dc7cc934d46366aa12ebf7b13f239e8699eacb;hb=HEAD

### CODE REVIEW

**Review by bhufmann — CHANGES_REQUESTED** [review]
Multiple tests are failing (see GitHub actions output) with errors that are probably related to this change. Could you please look into this? Thanks

**Comment by arfio** [comment]
Writing traces is failing because the context header struct definition is missing when reading the index files. This struct definition is needed when trimming the traces among other use cases. Is there any way of reconstructing that definition elsewhere, or should we just use the index files to calculate the end time and not store it for now ?

**Comment by bhufmann** [comment]
> Writing traces is failing because the context header struct definition is missing when reading the index files. This struct definition is needed when trimming the traces among other use cases. Is there any way of reconstructing that definition elsewhere, or should we just use the index files to calculate the end time and not store it for now ?

@MatthewKhouzam  any suggestions?

**Comment by MatthewKhouzam** [comment]
We have discussed this offline, here is the results:

1. Read the index files. You only care about the packet starts.
2. Read the metadata
3. Quickly populate with any known index locations from the CTF stream

This should fix any issue.

**Review by MatthewKhouzam — DISMISSED** [review]
I wrote this, I feel odd approving it.

**Review by MatthewKhouzam — COMMENTED** [review]
TraceReadAllTracesTest.readTraces:108 DJANGO_CLIENT Trace read error k_0
  TraceReadAllTracesTest.readTraces:108 DJANGO_DB Trace read error k_0
  TraceReadAllTracesTest.readTraces:108 DJANGO_HTTPD Trace read error k_0

**Comment by arfio** [comment]
> TraceReadAllTracesTest.readTraces:108 DJANGO_CLIENT Trace read error k_0 TraceReadAllTracesTest.readTraces:108 DJANGO_DB Trace read error k_0 TraceReadAllTracesTest.readTraces:108 DJANGO_HTTPD Trace read error k_0

This is due to a mismatch in index file version, I now throw if the minor is different, and I skip reading the index file.

**Review by MatthewKhouzam — APPROVED** [review]

**Review by bhufmann — APPROVED** [review]
The errors are gone. I opened a couple of LTTng CTF traces and non-LTTng CTF traces and they both work. Thanks for the contribution.

**Pull request merged**
